/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AbnormalitiesDetail: typeof import('./src/components/inspections/abnormalitiesDetail.vue')['default']
    AccessForm: typeof import('./src/components/forms/accessForm.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    copy: typeof import('./src/components/forms/newMethod copy.vue')['default']
    DailyAbnormalReport: typeof import('./src/components/forms/dailyAbnormalReport.vue')['default']
    DailyInspections: typeof import('./src/components/inspections/dailyInspections.vue')['default']
    EditInsItem: typeof import('./src/components/forms/editInsItem.vue')['default']
    EditMethod: typeof import('./src/components/forms/editMethod.vue')['default']
    EditRole: typeof import('./src/components/forms/editRole.vue')['default']
    EditTool: typeof import('./src/components/forms/editTool.vue')['default']
    EditType: typeof import('./src/components/forms/editType.vue')['default']
    EditUser: typeof import('./src/components/forms/editUser.vue')['default']
    EnvExample: typeof import('./src/components/EnvExample.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    InsItem: typeof import('./src/components/tables/insItem.vue')['default']
    InspectionComp: typeof import('./src/components/inspections/inspectionComp.vue')['default']
    LoginForm: typeof import('./src/components/forms/loginForm.vue')['default']
    MonthlyInspection: typeof import('./src/components/inspections/monthlyInspection.vue')['default']
    NewInsItem: typeof import('./src/components/forms/newInsItem.vue')['default']
    NewMethod: typeof import('./src/components/forms/newMethod.vue')['default']
    NewRole: typeof import('./src/components/forms/newRole.vue')['default']
    NewTool: typeof import('./src/components/forms/newTool.vue')['default']
    NewType: typeof import('./src/components/forms/newType.vue')['default']
    NewUser: typeof import('./src/components/forms/newUser.vue')['default']
    Pdf: typeof import('./src/components/pdf.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tables: typeof import('./src/components/tables.vue')['default']
    ToolData: typeof import('./src/components/forms/toolData.vue')['default']
    ToolImage: typeof import('./src/components/forms/toolImage.vue')['default']
    Types: typeof import('./src/components/tables/types.vue')['default']
    UploadSign: typeof import('./src/components/forms/uploadSign.vue')['default']
    WeeklyInspection: typeof import('./src/components/inspections/weeklyInspection.vue')['default']
  }
}
