/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/dashboard/': RouteRecordInfo<'/dashboard/', '/dashboard', Record<never, never>, Record<never, never>>,
    '/inspections/abnormalities': RouteRecordInfo<'/inspections/abnormalities', '/inspections/abnormalities', Record<never, never>, Record<never, never>>,
    '/inspections/daily': RouteRecordInfo<'/inspections/daily', '/inspections/daily', Record<never, never>, Record<never, never>>,
    '/inspections/monthly': RouteRecordInfo<'/inspections/monthly', '/inspections/monthly', Record<never, never>, Record<never, never>>,
    '/inspections/pdfreport': RouteRecordInfo<'/inspections/pdfreport', '/inspections/pdfreport', Record<never, never>, Record<never, never>>,
    '/inspections/weekly': RouteRecordInfo<'/inspections/weekly', '/inspections/weekly', Record<never, never>, Record<never, never>>,
    '/setups/roles': RouteRecordInfo<'/setups/roles', '/setups/roles', Record<never, never>, Record<never, never>>,
    '/setups/tools': RouteRecordInfo<'/setups/tools', '/setups/tools', Record<never, never>, Record<never, never>>,
    '/setups/users': RouteRecordInfo<'/setups/users', '/setups/users', Record<never, never>, Record<never, never>>,
  }
}
